"""The CERT insider-threat data as it actually arrives, written down once.

Release r4.2 ships six activity files and two context files. They share no
common key beyond ``user`` and a timestamp, they use three different date
formats between releases, and none of them is sorted. Every downstream module
in this package reads its column names from here rather than hard-coding
strings, because the r5 and r6 releases move columns around and a project that
only works on one release is not a portable one.

    logon.csv        id, date, user, pc, activity            (Logon | Logoff)
    device.csv       id, date, user, pc, activity            (Connect | Disconnect)
    file.csv         id, date, user, pc, filename, content
    http.csv         id, date, user, pc, url, content
    email.csv        id, date, user, pc, to, cc, bcc, from, size,
                     attachments, content
    psychometric.csv employee_name, user_id, O, C, E, A, N
    LDAP/*.csv       employee_name, user_id, email, role, business_unit,
                     functional_unit, department, team, supervisor

The LDAP directory holds one snapshot per month, which matters more than it
looks: people change role mid-study, and a model that pins everyone to their
January role will call a legitimate promotion an anomaly. The loader keeps the
snapshots separate and resolves a user's context as of the day being scored.

A note on what these files are. The data is synthetic — generated by ExactData
under DARPA sponsorship to look like a 1,000-person organisation over roughly
seventeen months, with a small number of scripted insider campaigns planted in
it. That is a real limitation and it is stated plainly in the data card rather
than buried. It is also, as of writing, the only openly available dataset that
carries genuine per-user behaviour, free text, and organisational context for
the same people over a long enough period to study how a campaign unfolds.
"""

from __future__ import annotations

from dataclasses import dataclass

# --------------------------------------------------------------------------
# activity streams
# --------------------------------------------------------------------------
ACTIVITY_FILES = ["logon", "device", "file", "http", "email"]

COLUMNS: dict[str, list[str]] = {
    "logon": ["id", "date", "user", "pc", "activity"],
    "device": ["id", "date", "user", "pc", "activity"],
    "file": ["id", "date", "user", "pc", "filename", "content"],
    "http": ["id", "date", "user", "pc", "url", "content"],
    "email": ["id", "date", "user", "pc", "to", "cc", "bcc", "from",
              "size", "attachments", "content"],
    "psychometric": ["employee_name", "user_id", "O", "C", "E", "A", "N"],
    "ldap": ["employee_name", "user_id", "email", "role", "business_unit",
             "functional_unit", "department", "team", "supervisor"],
}

#: Columns that carry natural language. These are the second modality, and
#: they are also the reason the release is enormous — http.csv alone is
#: 28 million rows of page text, over 14 GB extracted.
TEXT_COLUMNS = {"file": "content", "http": "content", "email": "content"}


# --------------------------------------------------------------------------
# the event vocabulary
# --------------------------------------------------------------------------
#: Every action becomes one of these tokens. The vocabulary is deliberately
#: small: the model should learn that *copying a file to a thumb drive at
#: 2am from someone else's machine* is unusual from the combination of token,
#: hour and machine flags, not from a token so specific that it has memorised
#: the answer. Twelve tokens plus three special ones.
EVENT_TOKENS = [
    "<pad>",
    "<mask>",
    "<cls>",
    "logon",
    "logoff",
    "device_connect",
    "device_disconnect",
    "file_open",
    "file_copy_to_removable",
    "http_visit",
    "email_send_internal",
    "email_send_external",
    "email_receive",
    "email_send_with_attachment",
]
TOKEN_TO_ID = {tok: i for i, tok in enumerate(EVENT_TOKENS)}
PAD_ID = TOKEN_TO_ID["<pad>"]
MASK_ID = TOKEN_TO_ID["<mask>"]
CLS_ID = TOKEN_TO_ID["<cls>"]
N_EVENT_TOKENS = len(EVENT_TOKENS)

#: Per-event covariates carried alongside the token. Kept to five because
#: every one of them has to be defensible as something a SIEM would actually
#: have, and because a wide per-event feature vector is where leakage hides.
EVENT_COVARIATES = [
    "hour",              # 0-23, embedded not scaled
    "is_after_hours",    # outside 07:00-19:00
    "is_weekend",
    "is_own_pc",         # the machine this user logs into most often
    "is_shared_pc",      # a machine used by more than five people
]


# --------------------------------------------------------------------------
# organisational context
# --------------------------------------------------------------------------
#: Categorical context from LDAP. `role` is the one that carries the peer
#: structure the whole method is built on.
CONTEXT_CATEGORICAL = ["role", "business_unit", "functional_unit",
                       "department", "team"]

#: Continuous context: the Big Five scores from psychometric.csv, plus two
#: derived organisational facts.
CONTEXT_NUMERIC = ["O", "C", "E", "A", "N", "is_supervisor", "team_size"]

#: The attribute that defines a peer group. Everything in this project turns
#: on the claim that "unusual" is only meaningful relative to a comparison
#: class, and that the right class is the one the organisation itself defines.
PEER_KEY = "role"


# --------------------------------------------------------------------------
# labels
# --------------------------------------------------------------------------
#: r4.2 contains three scripted campaigns. The answer files name the malicious
#: events; the scenario number is what makes a per-scenario breakdown possible,
#: and it matters because they are not equally hard.
SCENARIOS = {
    1: "Logs in after hours, copies data to a thumb drive, leaves the company",
    2: "Browses job sites, then steals data on the way out",
    3: "A disgruntled sysadmin plants a logic bomb after downloading keylogging tools",
}


@dataclass(frozen=True)
class ArtifactSpec:
    """What the local preparation step must produce for the modelling step.

    The raw release cannot be moved off the machine that downloaded it — it is
    too large and there is no reason to. ``scripts/prepare_local.py`` reduces
    it to these five arrays, which are two orders of magnitude smaller and
    contain no raw text, and those are what the model trains on.
    """

    events: str = "events.npz"          # int16 token ids + covariates per user-day
    content: str = "content.npy"        # float16 text embeddings per user-day
    context: str = "context.csv.gz"    # one row per user, resolved per month
    index: str = "index.csv.gz"          # user, date, split, label, scenario
    manifest: str = "manifest.json"     # provenance, hashes, encoder used


ARTIFACTS = ArtifactSpec()
